New 3 checkpoint
KristinaKulabuhova/MiniJava_Interpreter pull request #1
Opened 2021-04-28 20:04 UTC by KristinaKulabuhova

2021-04-28 21:00 UTC, Disadvantaged requested changes
Неплохая работа проделана, так держать!
Есть некоторые недочёты, и также некоторые вещи, которые, думаю, было бы удобнее написать по-другому.
Мне немного не нравится ещё, что у вас много отладочных комментариев. Лучше всё же не оставлять его в коммит версии.
После исправлений можно считать, что первые 2 чекпоинта готовы!

2021-04-28 21:00 UTC, Disadvantaged commented on ExecBlocks/AssertExpr.cpp
> +    delete expression;
Неплохо, что подчищаете память за собой.
Было бы удобнее, если бы это было сделано в виде отдельного визитора, а то так слишком размазано получилось это удаление по всем файлам.

2021-04-28 21:00 UTC, Disadvantaged commented on ExecBlocks/VariableDeclaration.h
> +  VarTypeStr *type_;
Кажется, тут утекает память

2021-04-28 21:00 UTC, Disadvantaged commented on Expressions/VarType.h
> +enum VarType
Зачем же вам этот enum, если в конце концов хардкодите константы в парсере:с

2021-04-28 21:00 UTC, Disadvantaged commented on MainElements/Class.h
> +  public:
Это, конечно, удобно делать все поля у классов публичными, но тогда вы фиксируетесь на внутреннем устройстве каждого класса. Из-за этого любое изменение обходится дороже -- приходится переписать не только цпп-шник, но ещё и все места, где вы используете эту переменную. 
Ваш код должен зависеть на абстракциях, а не конкретных реализациях

2021-04-28 21:00 UTC, Disadvantaged commented on MainElements/Class.h
> +  public:
Публичное API всё же было бы удобнее сделать в формате геттеров / сеттеров допустим.

2021-04-28 21:00 UTC, Disadvantaged commented on MainElements/Class.cpp
> +    for (std::variant<MethodDeclaration*, VariableDeclaration*>& declaration : decl_list->declarations) {
auto& выглядело бы лучше

2021-04-28 21:00 UTC, Disadvantaged commented on SubsidiaryClasses/DeclarationList.h
> +  std::vector<std::variant<MethodDeclaration *, VariableDeclaration *>> declarations;
Кажется, вместо variant-а на указателях было бы логичней заиспользовать dynamic_cast

2021-04-28 21:00 UTC, Disadvantaged commented on SubsidiaryClasses/ExprList.h
> +  ~ExprList() = default;
Выглядит как ещё одна утечка памяти.

2021-04-28 21:00 UTC, Disadvantaged commented on driver.cpp
> +// int Driver::Evaluate()
Обязательны ли эти комментарии? Их довольно много разбросано по всему проекту и я не совсем уверен в их надобности.

2021-04-28 21:00 UTC, Disadvantaged commented on main.cpp
> +// int main(int argc, char** argv) {
Зочем 2 одинаковых мейна?

2021-04-28 21:00 UTC, Disadvantaged commented on driver.hh
>      Program* program;
Кажется, вся ваша конструкция с раскиданными деструкторами не будет работать, если не удаляется program, которая, как раз, не удаляется...

2021-04-29 00:13 UTC, KristinaKulabuhova commented on Expressions/VarType.h
> +enum VarType
Просто так понятнее, что под каждой константой лежит

2021-05-02 09:02 UTC, Disadvantaged commented on Expressions/VarType.h
> +enum VarType
Ну тогда уж можно использовать сам enum, а не константы)

2021-05-02 09:07 UTC, Disadvantaged approved these changes
Классно получилось!

2021-05-05 10:34 UTC, merged